config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#home", as: "root"

  get "/help", to: "static_pages#help", as: "help"

  get "/about", to: "static_pages#about", as: "about"

  get "/contact", to: "static_pages#contact", as: "contact"

  get "/signup", to: "users#new", as: "signup"

  resources :users

  resources :sessions, only: [:new, :create]

  get "login", to: 'sessions#new'
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { |user| user.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :password, presence: true , length: { minimum: 8 }, on: :create

  validates :password_confirmation, presence: true, on: :create

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to the TDD demo-app!"
      redirect_to @user
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "A user has been removed."
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="container">
    <div class="row">
        <div class="col-lg-8">
            <p>Copyright &copy; spacemonkeythe 2014</p>
        </div>
        <nav class="pull-right col-lg-4">
          <ul>
            <li><%= link_to "About Me", about_path %></li>
            <li><%= link_to "Contact Me", contact_path %></li>
            <li><%= link_to "News", "http://news.railstutorial.org/" %></li>
          </ul>
        </nav>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <%= link_to "TDD/demo-app", root_path, id: "logo", class: "navbar-brand" %>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" id="dropdown-toggle" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter rip-off | <%= yield(:title) %></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="bower_components/html5shiv/dist/html5shiv.js"></script>
  <![endif]-->
</head>
  <body>

  <%= render "layouts/header" %>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

    <hr>
    <%= render "layouts/footer" %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(user.errors.count, "error") %>.
    </div>
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About Me</h1>

app/views/static_pages/contact.html.erb
<h1>Contact Me</h1>

app/views/static_pages/help.html.erb
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron hero-spacer">
  <h1 class="text-center">Welcome to TDD demo-app</h1>

  <h2>
    This is the home page for the <a href="https://twitter.com/spacemonkeyThe">spacemonkeythe's</a> sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1 class="form-signin-heading center">Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for @user, html: {class: "form-signup" } do |f| %>
      <%= render partial: "shared/error_messages", locals: { user: @user } %>
      <div class="form-group">
        <%= f.label :name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email, class: "control-label" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <%= f.submit "Update my account", class: "btn btn-large btn-primary" %>

      <div class="pull-right">
        <%= link_to "Cancel", user_path(@user) %>
      </div>

      <% if current_user?(@user) %>
    |   <%= link_to "delete", @user, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
    <% end %> 

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1 class="form-signin-heading center">Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for @user, html: {class: "form-signup" } do |f| %>
      <%= render partial: "shared/error_messages", locals: { user: @user } %>
      <div class="form-group">
        <%= f.label :name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email, class: "control-label" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password, class: "control-label" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confiramtion, "Confirmation", class: "control-label" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

      <div class="pull-right">
        <%= link_to "Cancel", root_path  %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<%= gravatar_for @user %>
<h1><%= @user.name %></h1>